Update Afleidingen.tex
debber1/Afleidingen_TG pull request #6
Opened 2022-04-07 16:15 UTC by sydon1

2de emacht hoort daar ni te staan int begin, komt pas opt einde wnr je er door deelt, zie notities prof rond min 6.

2022-04-07 17:13 UTC, debber1 requested changes

2022-04-07 17:13 UTC, debber1 commented on Samenvatting/Afleidingen.tex
> -waarbij $\widetilde{F} = F_0e^{i\omega t}e^{-i\varphi}$.
Laat de . hier staan ipv hem weg te doen

2022-04-07 17:14 UTC, debber1 commented
sydon, alles ziet er goed uit! gewoon de verandering toe passen en ik zal mergen

2022-04-08 11:32 UTC, sydon1 commented
kdenk da ik het heb gedaan

2022-04-08 12:43 UTC, closed without merging